words = ['ball','blast','smoke','hell','flash','inhale','trust','fog','interference','disaster','a disaster','a sense','sense','deal','evil','far','front','laugh','put','resident','robber','to rob','to reach','to sense',
	 'stuck','keep','breath','steel','awesome','habit','healthy','bulletproof','addiction','inhibited','substance','wind','completely','lungs','respect','calm','deep','throat','blade','truly','weapons','combat','close',
	 'bullet','still','fork','steel','sin','innocent','lift','fear','peer','verbs','nouns','particular','corner','stranded','stranding','mortal','enough',
	 'advertisement','endless',"What's the score",'score','shout','in favour of','unfortunately','tie','prepare','get rid of','rooster','no way','have (something) against','riled (up)','to waste of','person','thought','apartment','goalie'
	 ,'imaginary','has (something) to do with','What does it have to do with','pet peeve','alone','freak out','Are you nuts','nuts','government','freedom','make a decision','pending'];
words_ = ['ball','blast','smoke','hell','flash','inhale','trust','fog','interference','disaster','a disaster','a sense','sense','deal','evil','far','front','laugh','put','resident','robber','to rob','to reach','to sense',
	 'stuck','keep','breath','steel','awesome','habit','healthy','bulletproof','addiction','inhibited','substance','wind','completely','lungs','respect','calm','deep','throat','blade','truly','weapons','combat','close',
	 'bullet','still','fork','steel','sin','innocent','lift','fear','peer','verbs','nouns','particular','corner','stranded','stranding','mortal','enough',
	 'advertisement','endless',"What's the score",'score','shout','in favour of','unfortunately','tie','prepare','get rid of','rooster','no way','have (something) against','riled (up)','to waste of','person','thought','apartment','goalie'
	 ,'imaginary','has (something) to do with','What does it have to do with','pet peeve','alone','freak out','Are you nuts','nuts','government','freedom','make a decision','pending'];

let rru_words = {   
	'ball':'мяч',
	'blast':'взрыв',
	'smoke':'дым',
	'hell':'ад',
	'flash':'вспышка',
	'inhale':'вдох',
	'trust':'доверие',
	'fog':'туман',
	'interference':'помехи',
	'disaster':'бедствие',
	'a disaster':'катастрофа',
	'a sense':'смысл',
	'sense':'чувство',
	'deal':'сделка, договорились!',
	'evil':'злой',
	'far':'даль',
	'front':'перед',
	'laugh':'смех',
	'put':'класть',
	'resident':'постоялец',
	'robber':'грабитель',
	'to rob':'грабить',
	'to reach':'достичь',
	'to sense':'чувствать',
	'stuck':'застрять',
	'keep':'держать, сохранять',
	'breath':'дыхание',
	'wind':'ветер',
	'truly':'правдиво, действительно',
	'awesome':'здорово, круто',
	'habit':'привычка',
	'inhibited':'заторможеный, замкнутый',
	'healthy':'здоровый',
	'addiction':'зависимость, наркомания',
	'substance':'содержание, вещество',
	'completely':'полностью, совершенно, законченый',
	'lungs':'лёгкие',
	'respect':'уважение',
	'calm':'спокойствие, затишье',
	'deep':'глубина, глубоко',
	'throat':'горло',
	'blade':'лезвие',
	'weapons':'оружие',
	'combat':'боевой, бой',
	'close':'близко, закрывать',
	'bullet':'пуля',
	'bulletproof':'пуленепробиваемый',
	'still':'по-прежнему, всё ещё',
	'fork':'вилка',
	'steel':'сталь',
	'sin':'грех',
	'innocent':'невинный, невиновный',
	'lift':'поднимать, лифт',
	'fear':'страх, бояться',
	'peer':'всматриваться, равный, сверсник',
	'verbs':'глаголы',
	'nouns':'существительные',
	'particular':'особый, конкретный',
	'corner':'угол',
	'stranded':'скрученный',
	'stranding':'скручивание',
	'mortal':'смертный, смертельный',
	'enough':'достаточно',
	'advertisement':'рекламное объявление',
	'endless':'бесконечный',
	"What's the score":'Какой сейчас счёт?',
	'score':'очко, счёт',
	'shout':'крик, кричать',
	'in favour of':'в пользу...',
	'unfortunately':'к сожалению',
	'tie':'галстук, связать, ничья',
	'prepare':'подготовить',
	'get rid of':'избавиться',
	'rooster':'петух',
	'no way':'ни за что',
	'have (something) against':'иметь (что-то) против...',
	'riled (up)':'раздражать (взбесить)',
	'to waste of':'тратить впустую...',
	'person':'человек',
	'thought':'мысль',
	'apartment':'квартира',
	'goalie':'вратарь',
	'imaginary':'воображаемый',
	'has (something) to do with':'(что-то) связаное с...',
	'What does it have to do with':'Какое это имеет отношение к...',
	'pet peeve':'то что раздражает...',
	'alone':'только, в одиночестве, один',
	'freak out':'испугаться, злиться',
	'Are you nuts':'Ты сошёл с ума?',
	'nuts':'орешки',
	'government':'правительство',
	'freedom':'свобода',
	'make a decision':'принять решение',
	'pending':'в ожидании',
	'':'',
	'':'',
	'':'',
	'':'',
	'':'',
	'':'',
	'':'',
	'':'',
	'':'',
	'':'',
	'':'',
	'':'',
	'':'',
	'':''
}