words = ['ball','blast','smoke','hell','flash','inhale','trust','fog','interference','disaster','a disaster','a sense','sense','deal','evil','far','front','laugh','put','resident','robber','to rob','to reach','to sense',
	 'stuck','keep','breath','steel','awesome','habit','healthy','bulletproof','addiction','inhibited','substance','wind','completely','lungs','respect','calm','deep','throat','blade','truly','weapons','combat','close',
	 'bullet','still','fork','steel','sin','innocent','lift','fear','peer','verbs','nouns','particular','corner','stranded','stranding','mortal','enough'];  

let rru_words = {   
	'ball':'мяч',
	'blast':'взрыв',
	'smoke':'дым',
	'hell':'ад',
	'flash':'вспышка',
	'inhale':'вдох',
	'trust':'доверие',
	'fog':'туман',
	'interference':'помехи',
	'disaster':'бедствие',
	'a disaster':'катастрофа',
	'a sense':'смысл',
	'sense':'чувство',
	'deal':'сделка',
	'evil':'злой',
	'far':'даль',
	'front':'перед',
	'laugh':'смех',
	'put':'класть',
	'resident':'постоялец',
	'robber':'грабитель',
	'to rob':'грабить',
	'to reach':'достичь',
	'to sense':'чувствать',
	'stuck':'застрять',
	'keep':'держать, сохранять',
	'breath':'дыхание',
	'wind':'ветер',
	'truly':'правдиво, действительно',
	'awesome':'здорово',
	'habit':'привычка',
	'inhibited':'заторможеный, замкнутый',
	'healthy':'здоровый',
	'addiction':'зависимость, наркомания',
	'substance':'содержание, вещество',
	'completely':'полностью, совершенно, законченый',
	'lungs':'лёгкие',
	'respect':'уважение',
	'calm':'спокойствие, затишье',
	'deep':'глубина, глубоко',
	'throat':'горло',
	'blade':'лезвие',
	'weapons':'оружие',
	'combat':'боевой, бой',
	'close':'близко, закрывать',
	'bullet':'пуля',
	'bulletproof':'пуленепробиваемый',
	'still':'по-прежнему, всё ещё',
	'fork':'вилка',
	'steel':'сталь',
	'sin':'грех',
	'innocent':'невинный, невиновный',
	'lift':'поднимать, лифт',
	'fear':'страх, бояться',
	'peer':'всматриваться, равный, сверсник',
	'verbs':'глаголы',
	'nouns':'существительные',
	'particular':'особый, конкретный',
	'corner':'угол',
	'stranded':'скрученный',
	'stranding':'скручивание',
	'mortal':'смертный, смертельный',
	'enough':'достаточно',
	'':'',
	'':'',
	'':'',
	'':'',
	'':'',
	'':'',
	'':'',
	'':'',
	'':'',
	'':'',
	'':'',
	'':'',
	'':'',
	'':'',
	'':'',
	'':'',
	'':'',
	'':'',
	'':'',
	'':'',
	'':'',
	'':'',
	'':'',
	'':'',
	'':'',
	'':'',
	'':'',
	'':'',
	'':'',
	'':'',
	'':'',
	'':'',
	'':'',
	'':'',
	'':'',
	'':'',
	'':'',
	'':'',
	'':'',
	'':'',
	'':'',
	'':'',
	'':'',
	'':'',
	'':''
}
